sudo: required
language: go
go:
  - "1.11.x"
matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode8

install:
  # Install gox
  - go get github.com/mitchellh/gox
  - go get -t ./...
  - make install-linters
script:
  - make lint
  - make build


notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
